export const INDUSTRIES = [
  'Affiliate Marketing',
  'Agriculture',
  'Automotive',
  'Baby & Kids',
  'Beauty & Personal Care',
  'Coupon Marketing',
  'E-commerce / D2C',
  'Education & EdTech',
  'Electronics & Tech',
  'Entertainment & Media',
  'Fashion & Apparel',
  'Finance & Insurance',
  'Food & Beverages',
  'Health & Wellness',
  'Home & Living',
  'Jewellery & Accessories',
  'Pets & Animals',
  'Real Estate',
  'SaaS / B2B',
  'Sports & Fitness',
  'Travel & Hospitality',
] as const;

export const TONES = [
  'Warm & friendly',
  'Witty & playful',
  'Premium & refined',
  'Bold & energetic',
  'Calm & reassuring',
  'Professional & trustworthy',
  'Youthful & trendy',
  'Traditional & cultural',
  'Minimalist & clean',
  'Quirky & fun',
] as const;

export const LANGUAGES = [
  'English',
  'Hinglish (Hindi + English)',
  'Hindi',
  'Tamil',
  'Telugu',
  'Bengali',
  'Marathi',
  'Kannada',
  'Malayalam',
  'Gujarati',
  'Punjabi',
] as const;
